package WWW::SwaggerClient::Object::CallReport;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#Call Report\n            PhoneNumber, \n            Caller name(optional), \n            Call category(optional), \n            Comment or tags(free text) (optional), \n            Unwanted call  - yes/no(optional),
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->swagger_types( {
    'phone_number' => 'string',
    'reported_caller_name' => 'string',
    'reported_caller_id' => 'string',
    'caller_type' => 'string',
    'comment' => 'string',
    'unwanted_call' => 'boolean',
    'call_time' => 'DateTime'
} );

__PACKAGE__->attribute_map( {
    'phone_number' => 'PhoneNumber',
    'reported_caller_name' => 'ReportedCallerName',
    'reported_caller_id' => 'ReportedCallerId',
    'caller_type' => 'CallerType',
    'comment' => 'Comment',
    'unwanted_call' => 'UnwantedCall',
    'call_time' => 'CallTime'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
