package WWW::SwaggerClient::Object::CallReport;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#Call Report\r\n            PhoneNumber, \r\n            Caller name(optional), \r\n            Call category(optional), \r\n            Comment or tags(free text) (optional), \r\n            Unwanted call  - yes/no(optional),
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::SwaggerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'Call Report\r\n            PhoneNumber, \r\n            Caller name(optional), \r\n            Call category(optional), \r\n            Comment or tags(free text) (optional), \r\n            Unwanted call  - yes/no(optional),',
                                  class => 'CallReport',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'phone_number' => {
    	datatype => 'string',
    	base_name => 'PhoneNumber',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'reported_caller_name' => {
    	datatype => 'string',
    	base_name => 'ReportedCallerName',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'reported_caller_id' => {
    	datatype => 'string',
    	base_name => 'ReportedCallerId',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'caller_type' => {
    	datatype => 'string',
    	base_name => 'CallerType',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'comment' => {
    	datatype => 'string',
    	base_name => 'Comment',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'unwanted_call' => {
    	datatype => 'boolean',
    	base_name => 'UnwantedCall',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'call_time' => {
    	datatype => 'DateTime',
    	base_name => 'CallTime',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'reporter' => {
    	datatype => 'string',
    	base_name => 'Reporter',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'ip_address' => {
    	datatype => 'string',
    	base_name => 'IpAddress',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'latitude' => {
    	datatype => 'double',
    	base_name => 'Latitude',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'longitude' => {
    	datatype => 'double',
    	base_name => 'Longitude',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'phone_number' => 'string',
    'reported_caller_name' => 'string',
    'reported_caller_id' => 'string',
    'caller_type' => 'string',
    'comment' => 'string',
    'unwanted_call' => 'boolean',
    'call_time' => 'DateTime',
    'reporter' => 'string',
    'ip_address' => 'string',
    'latitude' => 'double',
    'longitude' => 'double'
} );

__PACKAGE__->attribute_map( {
    'phone_number' => 'PhoneNumber',
    'reported_caller_name' => 'ReportedCallerName',
    'reported_caller_id' => 'ReportedCallerId',
    'caller_type' => 'CallerType',
    'comment' => 'Comment',
    'unwanted_call' => 'UnwantedCall',
    'call_time' => 'CallTime',
    'reporter' => 'Reporter',
    'ip_address' => 'IpAddress',
    'latitude' => 'Latitude',
    'longitude' => 'Longitude'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
