package WWW::SwaggerClient::Object::DoNotCallComplaints;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#Free service (with registration) which serves Government Do Not Call data via API \n            Search via phone number returns available data, reported name, total complaints
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->swagger_types( {
    'reported_caller_name' => 'string',
    'total_number_of_complaints' => 'int',
    'complaints_by_gov_entity' => 'HASH[string,int]',
    'last_compaint_date' => 'DateTime',
    'tags' => 'ARRAY[string]'
} );

__PACKAGE__->attribute_map( {
    'reported_caller_name' => 'ReportedCallerName',
    'total_number_of_complaints' => 'TotalNumberOfComplaints',
    'complaints_by_gov_entity' => 'ComplaintsByGovEntity',
    'last_compaint_date' => 'LastCompaintDate',
    'tags' => 'Tags'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});

1;
