=begin
Call Control API

API for blocking phone calls with Call Control. Data is from crowdsourced community blacklist from 12+ million users and government agencies (FTC, FCC, IRS) Try with api_key 'demo', hit explore above, and then try phone numbers 18008472911,13157244022,17275567300,18008276655,12061231234.

OpenAPI spec version: 2015-11-01
Contact: info@kedlin.com
Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::EnterpriseApiApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EnterpriseApiApi' do
  before do
    # run before each test
    @instance = SwaggerClient::EnterpriseApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EnterpriseApiApi' do
    it 'should create an instact of EnterpriseApiApi' do
      @instance.should be_a(SwaggerClient::EnterpriseApiApi)
    end
  end

  # unit tests for enterprise_api_get_block_list
  # Enterprise  GET: GetBlockList\r\n            Simple Enteprise which returns the current and complete list of numbers that the network is blocking
  # All \r\n            Try with api_key &#39;demo&#39; for the demo block list (which will block 18008472911, 13157244022, 17275567300, 18008276655) but not 12061231234
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :cached 
  # @return [Array<String>]
  describe 'enterprise_api_get_block_list test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for enterprise_api_get_user
  # Enterprise  GET: GetUser\r\n            Returns the current information from the user
  # 
  # @param phone_number 
  # @param [Hash] opts the optional parameters
  # @return [CallControlUser]
  describe 'enterprise_api_get_user test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for enterprise_api_should_block
  # Enterprise  GET: ShouldBlock\r\n            Simple Enteprise which returns a call block proceed decision.
  # This returns information required to perform basic call blocking behaviors\r\n            Try with api_key &#39;demo&#39; and phone numbers 18008472911, 13157244022, 17275567300, 18008276655, and 12061231234 (last one not spam)
  # @param phone_number phone number to search
  # @param user_phone_number (OPTOPNAL) phone number of user to look up block rules
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'enterprise_api_should_block test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for enterprise_api_upsert_user
  # 
  # 
  # @param user 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'enterprise_api_upsert_user test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
