=begin
Call Control API

API for blocking phone calls with Call Control. Data is from crowdsourced community blacklist from 12+ million users and government agencies (FTC, FCC, IRS) Try with api_key 'demo', hit explore above, and then try phone numbers 18008472911,13157244022,17275567300,18008276655,12061231234.

OpenAPI spec version: 2015-11-01
Contact: info@kedlin.com
Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ReputationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReputationApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ReputationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReputationApi' do
    it 'should create an instact of ReputationApi' do
      @instance.should be_a(SwaggerClient::ReputationApi)
    end
  end

  # unit tests for reputation_report
  # Report: report spam calls received to better tune our algorithms based upon spam calls you receive
  # This returns information required to perform basic call blocking behaviors&lt;br /&gt;\r\n            Try with api_key &#39;demo&#39; and phone numbers 18008472911, 13157244022, 17275567300, 18008276655, and 12061231234 (last one not spam)
  # @param call_report [FromBody] Call Report\r\n            PhoneNumber, \r\n            Caller name(optional), \r\n            Call category(optional), \r\n            Comment or tags(free text) (optional), \r\n            Unwanted call  - yes/no(optional),
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'reputation_report test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for reputation_reputation
  # Reputation:\r\n            Premium service which returns a reputation informaiton of a phone number via API.
  # This returns information required to perform basic call blocking behaviors&lt;br /&gt;\r\n            Try with api_key &#39;demo&#39; and phone numbers 18008472911, 13157244022, 17275567300, 18008276655, and 12061231234 (last one not spam)
  # @param phone_number phone number to search
  # @param [Hash] opts the optional parameters
  # @return [Reputation]
  describe 'reputation_reputation test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
