#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGReporterLoation.h"


@protocol SWGCallReport
@end

@interface SWGCallReport : SWGObject


@property(nonatomic) NSString* phoneNumber;

@property(nonatomic) NSString* reportedCallerName;

@property(nonatomic) NSString* reportedCallerId;

@property(nonatomic) NSString* callerType;

@property(nonatomic) NSString* comment;

@property(nonatomic) NSNumber* unwantedCall;

@property(nonatomic) NSDate* callTime;

@property(nonatomic) NSString* reporter;

@property(nonatomic) SWGReporterLoation* reporterLoation;

@end
