#import <Foundation/Foundation.h>
#import "SWGDoNotCallComplaints.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGDoNotCallComplaintsApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGDoNotCallComplaintsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGDoNotCallComplaintsApi*) sharedAPI;
///
///
/// <br />\n<b>DoNotCallComplaints</b>\n<br />Free service (with registration), providing community and government complaint lookup by phone number for up to 2,000 queries per month.  Details include number complaint rates from (FTC, FCC, IRS, Indiana Attorney  General) and key entity tag extractions from complaints.
/// This is the main funciton to get data out of the call control reporting system<br />\n            Try with api_key 'demo' and phone number 12674070100 (spam) 12061231234 (not spam)
///
/// @param phoneNumber phone number to search
/// 
///
/// @return SWGDoNotCallComplaints*
-(NSNumber*) doNotCallComplaintsDoNotCallComplaintsWithCompletionBlock :(NSString*) phoneNumber 
    
    completionHandler: (void (^)(SWGDoNotCallComplaints* output, NSError* error))completionBlock;
    



@end
