#import <Foundation/Foundation.h>
#import "SWGCallControlUser.h"
#import "SWGObject.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGEnterpriseApiApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGEnterpriseApiApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGEnterpriseApiApi*) sharedAPI;
///
///
/// Enterprise  GET: GetBlockList\r\n            Simple Enteprise which returns the current and complete list of numbers that the network is blocking
/// All \r\n            Try with api_key 'demo' for the demo block list (which will block 18008472911, 13157244022, 17275567300, 18008276655) but not 12061231234
///
/// @param cached 
/// 
///
/// @return NSArray* /* NSString */
-(NSNumber*) enterpriseApiGetBlockListWithCached: (NSNumber*) cached
    completionHandler: (void (^)(NSArray* /* NSString */ output, NSError* error)) handler;


///
///
/// Enterprise  GET: GetUser\r\n            Returns the current information from the user
/// 
///
/// @param phoneNumber 
/// 
///
/// @return SWGCallControlUser*
-(NSNumber*) enterpriseApiGetUserWithPhoneNumber: (NSString*) phoneNumber
    completionHandler: (void (^)(SWGCallControlUser* output, NSError* error)) handler;


///
///
/// Enterprise  GET: ShouldBlock\r\n            Simple Enteprise which returns a call block proceed decision.
/// This returns information required to perform basic call blocking behaviors\r\n            Try with api_key 'demo' and phone numbers 18008472911, 13157244022, 17275567300, 18008276655, and 12061231234 (last one not spam)
///
/// @param phoneNumber phone number to search
/// @param userPhoneNumber (OPTOPNAL) phone number of user to look up block rules
/// 
///
/// @return NSString*
-(NSNumber*) enterpriseApiShouldBlockWithPhoneNumber: (NSString*) phoneNumber
    userPhoneNumber: (NSString*) userPhoneNumber
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


///
///
/// 
/// 
///
/// @param user 
/// 
///
/// @return SWGObject*
-(NSNumber*) enterpriseApiUpsertUserWithUser: (SWGCallControlUser*) user
    completionHandler: (void (^)(SWGObject* output, NSError* error)) handler;



@end
