#import <Foundation/Foundation.h>
#import "SWGCallReport.h"
#import "SWGReputation.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGReputationApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGReputationApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGReputationApi*) sharedAPI;
///
///
/// Report:</b> report spam calls received to better tune our algorithms based upon spam calls you receive
/// This returns information required to perform basic call blocking behaviors<br />\n            Try with api_key 'demo' and phone number 12674070100 (spam) 12061231234 (not spam)
///
/// @param callReport [FromBody] Call Report\n            PhoneNumber, \n            Caller name(optional), \n            Call category(optional), \n            Comment or tags(free text) (optional), \n            Unwanted call  - yes/no(optional),
/// 
///
/// @return 
-(NSNumber*) reputationReportWithCompletionBlock :(SWGCallReport*) callReport 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


///
///
/// <br />\n<b>Reputation</b>\n<br />\n            Premium service which returns a reputation informaiton of a phone number via API.
/// This returns information required to perform basic call blocking behaviors<br />\n            Try with api_key 'demo' and phone number 12674070100 (spam) 12061231234 (not spam)
///
/// @param phoneNumber phone number to search
/// 
///
/// @return SWGReputation*
-(NSNumber*) reputationReputationWithCompletionBlock :(NSString*) phoneNumber 
    
    completionHandler: (void (^)(SWGReputation* output, NSError* error))completionBlock;
    



@end
