=begin
Call Control API

API for blocking phone calls with Call Control. Data is from crowdsourced community blacklist from 12+ million users and government agencies (FTC, FCC, IRS) Try with api_key 'demo', hit explore above, and then try phone numbers 18008472911,13157244022,17275567300,18008276655,12061231234.

OpenAPI spec version: 2015-11-01
Contact: info@kedlin.com
Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class QuietHour
    attr_accessor :day_of_week_list

    attr_accessor :start_hour_local

    attr_accessor :start_min_local

    attr_accessor :duration_min

    attr_accessor :time_zone_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'day_of_week_list' => :'DayOfWeekList',
        
        :'start_hour_local' => :'StartHourLocal',
        
        :'start_min_local' => :'StartMinLocal',
        
        :'duration_min' => :'DurationMin',
        
        :'time_zone_name' => :'TimeZoneName'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'day_of_week_list' => :'Array<String>',
        :'start_hour_local' => :'Integer',
        :'start_min_local' => :'Integer',
        :'duration_min' => :'Integer',
        :'time_zone_name' => :'String'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'DayOfWeekList']
        if (value = attributes[:'DayOfWeekList']).is_a?(Array)
          self.day_of_week_list = value
        end
      end
      
      if attributes[:'StartHourLocal']
        self.start_hour_local = attributes[:'StartHourLocal']
      end
      
      if attributes[:'StartMinLocal']
        self.start_min_local = attributes[:'StartMinLocal']
      end
      
      if attributes[:'DurationMin']
        self.duration_min = attributes[:'DurationMin']
      end
      
      if attributes[:'TimeZoneName']
        self.time_zone_name = attributes[:'TimeZoneName']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          day_of_week_list == o.day_of_week_list &&
          start_hour_local == o.start_hour_local &&
          start_min_local == o.start_min_local &&
          duration_min == o.duration_min &&
          time_zone_name == o.time_zone_name
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [day_of_week_list, start_hour_local, start_min_local, duration_min, time_zone_name].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
