=begin
Call Control API

API for blocking phone calls with Call Control. Data is from crowdsourced community blacklist from 12+ million users and government agencies (FTC, FCC, IRS) Try with api_key 'demo', hit explore above, and then try phone numbers 18008472911,13157244022,17275567300,18008276655,12061231234.

OpenAPI spec version: 2015-11-01
Contact: info@kedlin.com
Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class Reputation
    attr_accessor :call_type

    attr_accessor :confidence

    attr_accessor :is_spam

    attr_accessor :last_compaint_date

    attr_accessor :reported_caller_name

    attr_accessor :tags

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'call_type' => :'CallType',
        
        :'confidence' => :'Confidence',
        
        :'is_spam' => :'IsSpam',
        
        :'last_compaint_date' => :'LastCompaintDate',
        
        :'reported_caller_name' => :'ReportedCallerName',
        
        :'tags' => :'Tags'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'call_type' => :'String',
        :'confidence' => :'Integer',
        :'is_spam' => :'BOOLEAN',
        :'last_compaint_date' => :'DateTime',
        :'reported_caller_name' => :'String',
        :'tags' => :'Array<String>'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'CallType']
        self.call_type = attributes[:'CallType']
      end
      
      if attributes[:'Confidence']
        self.confidence = attributes[:'Confidence']
      end
      
      if attributes[:'IsSpam']
        self.is_spam = attributes[:'IsSpam']
      end
      
      if attributes[:'LastCompaintDate']
        self.last_compaint_date = attributes[:'LastCompaintDate']
      end
      
      if attributes[:'ReportedCallerName']
        self.reported_caller_name = attributes[:'ReportedCallerName']
      end
      
      if attributes[:'Tags']
        if (value = attributes[:'Tags']).is_a?(Array)
          self.tags = value
        end
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          call_type == o.call_type &&
          confidence == o.confidence &&
          is_spam == o.is_spam &&
          last_compaint_date == o.last_compaint_date &&
          reported_caller_name == o.reported_caller_name &&
          tags == o.tags
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [call_type, confidence, is_spam, last_compaint_date, reported_caller_name, tags].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
